[tool.poetry]
name = "rememvr"
version = "0.1.0"
description = ""
authors = ["Richard <richard@etai.app>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
